name: chap_gpt
services:
  devcontainer:  
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    networks:
      - default
    volumes:
      - ../..:/workspaces:cached
networks:
  default: