name: chap_gpt
services:
  devcontainer:  
    image: mcr.microsoft.com/devcontainers/python:3.12      
    command: sleep infinity
    networks:
      - default
    volumes:
      - ../..:/workspaces:cached
networks:
  default: